name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pester:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - shell: pwsh
        run: |
          if ((Get-Module -Name Pester -ListAvailable | Sort-Object -Property Version -Descending | Select-Object -First 1 | ForEach-Object { $_.Version }) -lt '5.5') {
            Install-Module Pester -MinimumVersion 5.5 -Force -Scope CurrentUser -SkipPublisherCheck
          }
      - shell: pwsh
        run: |
          Import-Module Pester -MinimumVersion 5.5
          Invoke-Pester tests/powershell -CI
